spring:
  application:
    name: product

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.31.129:3306/springcloud?characterEncoding=UTF-8&useSSL=false

  # rabbitmq配置
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest

# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#ribbon超时时间设置
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000